language: php
php:
  - "5.6"
  - "5.5"

services:
  - mongodb

env:
  - PECLMONGO=mongo-1.6.10 PECLSOLR=solr-2.4.0

before_install:
  - sudo apt-get update > /dev/null
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"

install:
  # install php packages required for running YAWIK phpunit tests
  - sudo apt-get install -y --force-yes php5-intl php5-curl php5-xsl

  # add composer's global bin directory to the path
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
  # install Mongo extension
  - sh -c "wget http://pecl.php.net/get/$PECLMONGO.tgz"
  - sh -c "tar xfz $PECLMONGO.tgz"
  - sh -c "cd $PECLMONGO && phpize && ./configure && make && sudo make install"

  # install SOLR extension
  - sh -c "wget http://pecl.php.net/get/$PECLSOLR.tgz"
  - sh -c "tar xfz $PECLSOLR.tgz"
  - sh -c "cd $PECLSOLR && phpize && ./configure && make && sudo make install"

  - phpenv config-add .travis/phpenv.ini
  - ./install.sh -b .travis/build.properties.travis
  - ./composer.phar self-update
  - ./composer.phar create-project cross-solution/yawik
  - cd yawik
  - ../composer.phar require cross-solution/yawik-company-registration

script:
  - ln -s ../test/build/logs build
  - cd test
  - phpunit --configuration $TRAVIS_BUILD_DIR/test/phpunit.xml.dist

after_script:
  - cd $TRAVIS_BUILD_DIR
  - ls -l test/build/logs
  - php vendor/bin/coveralls -vvv
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover test/build/logs/clover.serialized

